CREATE TABLE IF NOT EXISTS customers (
    customer_id VARCHAR(20) PRIMARY KEY,
    document_number VARCHAR(20) NOT NULL UNIQUE,
    document_type VARCHAR(10) NOT NULL,
    first_name VARCHAR(100) NOT NULL,
    last_name VARCHAR(100) NOT NULL,
    date_of_birth DATE NOT NULL,
    gender VARCHAR(1),
    email VARCHAR(100),
    mobile_phone VARCHAR(20),
    landline_phone VARCHAR(20),
    address VARCHAR(200),
    city VARCHAR(100) NOT NULL,
    state VARCHAR(100) NOT NULL,
    country VARCHAR(50) NOT NULL,
    postal_code VARCHAR(10),
    detected_accent VARCHAR(50),
    segment VARCHAR(50) NOT NULL,
    credit_score INTEGER,
    estimated_monthly_income DECIMAL(12,2),
    occupation VARCHAR(100),
    marital_status VARCHAR(20),
    education_level VARCHAR(50),
    registration_date TIMESTAMP NOT NULL,
    registration_branch_id VARCHAR(20) NOT NULL,
    customer_status VARCHAR(20) NOT NULL,
    last_updated TIMESTAMP NOT NULL,
    accepts_marketing BOOLEAN NOT NULL
);
